name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: |
         touch .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
          echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> .env
          echo "IPINFO_AUTH_TOKEN=${{ secrets.IPINFO_AUTH_TOKEN }}" >> .env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PIN4SMS_KEY=${{ secrets.PIN4SMS_KEY }}" >> .env
          echo "PIN4SMS_ROUTE=${{ secrets.PIN4SMS_ROUTE }}" >> .env
          echo "PIN4SMS_SENDER_ID=${{ secrets.PIN4SMS_SENDER_ID }}" >> .env
          echo "PIN4SMS_TEMPLATE_ID=${{ secrets.PIN4SMS_TEMPLATE_ID }}" >> .env


      - name: Install dependencies
        run: npm install

      - name: Start or Restart server with PM2
        run:  |
          pm2 delete api || true
          pm2 start server.js --name api
          pm2 save

      - name: Run tests or server
        run: |
          echo "🚀 Add your test or start command here"
          # Example:
          # npm run test