name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Removed cache to avoid lock file error

      - name: Install dependencies
        run: npm install

      - name: Run your server or tests
        run: |
          touch .env
          echo "${{ secrets.BACKEND_ENV_FILE }}" > .env

      - name: Run your server or tests
        run: |
          echo "🚀 Add your test or start command here"
          # Example:
          # npm run test
